ipvar HOME_NET [10.10.0.0/24,10.20.0.0/24]
ipvar EXTERNAL_NET !$HOME_NET
ipvar DVWA_SERVER  10.10.0.10
ipvar REDIS_DB     10.20.0.20
portvar HTTP_PORTS 80
portvar REDIS_PORT 6379
var RULE_PATH /etc/snort/rules
output alert_full: alert
output log_unified2: filename merged.log, limit 128
preprocessor frag3_global: max_frags 65536
preprocessor frag3_engine: policy first detect_anomalies
preprocessor stream5_global: track_tcp yes, track_udp yes
preprocessor stream5_tcp: policy first, use_static_footprint_sizes
include $RULE_PATH/local.rules
